# Generated by Django 4.2 on 2026-05-15 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='borrow_date',
            field=models.DateField(default=datetime.date(2026, 5, 15)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='return_date',
            field=models.DateField(default=datetime.date(2026, 5, 15)),
            preserve_default=False,
        ),
    ]
