# Generated by Django 4.2 on 2026-05-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_borrowrequest_borrow_date_borrowrequest_return_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowrequest',
            options={'verbose_name': 'Borrow Request', 'verbose_name_plural': 'Borrow Requests'},
        ),
    ]
